version: "3.8"

services:
  orbitsync:
    build:
      context: .
      dockerfile: Dockerfile
    image: orbitsync:latest
    container_name: orbitsync
    restart: always
    ports:
      - "3000:3000"
    environment:
      # - NEXT_PUBLIC_SOME_API_URL=https://api.example.com
      - NODE_ENV=production
